### PR TITLE
Compile Dutch, Occitan and Ukrainian UI localizations

### PR DESCRIPTION
**Pull request by fitojb**
#20
LP: [#1940443](https://pad.lv/1940443)
LP: [#1960014](https://pad.lv/1960014)

### CODE REVIEW

**Comment by fitojb** [comment]
This fixes three user requests. Please merge to both 7.2 and 7.3 (7.2 still has one scheduled bugfix release upstream, so it’s still valuable)

**Comment by ricotz** [comment]
Please target the 7.3 branch. Currently we only ship the latest upstream stable release as snap.

**Comment by fitojb** [comment]
OK, if it’s going to be 7.3-only, then adding hunspell-oc is unblocked…

**Comment by fitojb** [comment]
Can’t get rid of the merge commit and I spent an hour already. Will open another PR.

**Comment by fitojb** [comment]
Opened PR #22 now.

**Pull request closed without merging**
